### ISSUE TITLE
Query regarding probability computation in enricher_internal function

### ISSUE THREAD

**Issue by soumitrakp** [YuLab-SMU/DOSE#73]
I was going through the code for computing probability in enricher_internal function. I have two queries:
1. Why k-1 as number of white balls drwan? Should it not be just k?
2. Why do you restrict universe to only those in the genesets?

I am trying to use enricher function in the following scenario. I have a set of sex-biased genes. I also have a list of genes that are transcription factors. I just want to test if the transcription factors are over represented in the sexbiased genes. Since there is only one geneset, enricher_internal simply restricts the given universe (set of all expressed genes) to set of transcription factors and it simply does not give a correct p-value.

**Comment by GuangchuangYu** [comment]
1. the p value is calculated by the probality of observing k or more than k.
2. because we assume that the gene sets is genome wide annotation. If it is not restricted to only those in the gene sets,  this equivalent to set those unknown annotation (we don't know, a.k.a, NA) to not in the gene set (as we know that, a.k.a., FALSE). 

I make sense in the situation you described here. So we now allows forcing the `universe` untouched by setting `options(enrichment_force_universe = TRUE)`.
